In [1]:
import aocd
import numpy as np

In [2]:
class BingoCard:
    def __init__(self, numbers: np.array):
        self.numbers = numbers
        self.entire_set = set(numbers.flatten())
        self.marked = set()
        self.winning = False
        
    def get_numbers(self):
        return self.numbers
    
    def get_unmarked(self):
        return self.entire_set.difference(self.marked)
    
    def mark(self, n):
        self.marked.add(n)
    
    def check_for_win(self):
        # Check columns and rows for each index
        for i in range(len(self.numbers)):
            if all([j in self.marked for j in self.numbers[i]]) or \
                all([j in self.marked for j in self.numbers[:, i]]):
                self.winning = True

In [3]:
def find_last(draws, cards):
    for draw in iter([int(i) for i in draws.split(',')]):
        for card in card_list:
            card.mark(draw)
            card.check_for_win()
        not_yet_winning = [c for c in card_list if not(c.winning)]
        if len(not_yet_winning) == 1:
            last_card = not_yet_winning[0]
        if len(not_yet_winning) == 0:
            return last_card, draw

In [4]:
# Setup
raw_data = aocd.get_data(day=4, year=2021)
clean_data = raw_data.split('\n\n')
draws, raw_cards = clean_data[0], clean_data[1:]
card_list = []
for card in raw_cards:
    rows = card.split('\n')
    card_arr = np.array([[int(num) for num in row.split()] for row in rows])
    new_card = BingoCard(card_arr)
    card_list.append(new_card)

In [5]:
winning_card, winning_draw = find_last(draws, card_list)

winning_unmarked = winning_card.get_unmarked()
print(winning_card.get_numbers())
print(winning_unmarked)
print(winning_draw)
score = sum(winning_unmarked) * winning_draw

[[26 47  2 22  9]
 [ 6 81 53 17 88]
 [58 25 55 31 19]
 [42 27 85 97 14]
 [64 52 66 63 51]]
{66, 9, 14, 81, 85, 25, 58}
31


In [6]:
print(score)

10478
